---
version: "3.9"
services:
  proxy:
    image: nginx:1.21.4-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

  api:
    build: .
    command: npx lerna run --scope api --stream start:prod
    ports:
      - 6969:6969/udp
    environment:
      - AUTH_USERNAME=${AUTH_USERNAME:-mgu-master}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-password}
      - ANSIBLE_INVENTORY=${ANSIBLE_INVENTORY:-/app/config/inventory.yml}
      - SECRET=${SECRET:-secret}
      - EXPIRES_IN=${EXPIRES_IN:-1h}
      - SECRET_REFRESH=${SECRET_REFRESH:-topsecret}
      - REFRESH_EXPIRES_IN=${REFRESH_EXPIRES_IN:-1d}
      - REFRESH_REMEMBER_EXPIRES_IN=${REFRESH_REMEMBER_EXPIRES_IN:-7d}
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY:-/app/config/lab229}
      - STATE_CHECK_INTERVAL=${STATE_CHECK_INTERVAL:-10}
      - TFTP_PORT=${TFTP_PORT:-6969}
      - GRUB_UBUNTU=${GRUB_UBUNTU:-0}
      - GRUB_WINDOWS=${GRUB_WINDOWS:-3}
      - WETTY_TARGET_URL=http://wetty:3001/
      - WETTY_PROXY_URL=/api/wetty
    volumes:
      - ./config:/app/config:ro

  front:
    build: .
    command: npx lerna run --scope front --stream start
    environment:
      - BASE_URL=/api/
      - BASE_URL_SOCKET=/

  wetty:
    image: wettyoss/wetty
    command: "wetty -p 3001 -b /api/wetty/ --allow-iframe --ssh-user ${SSH_USER:-pi}
      --ssh-host ${SSH_HOST:-192.168.0.141} --ssh-key
      ${SSH_PRIVATE_KEY:-/app/config/lab229} --ssh-auth publickey,password"
    volumes:
      - ./config:/app/config:ro
