---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 207.159.35.67
          mac_address: B5-BE-D6-34-57-F0
    worker:
      hosts:
        k8s-1:
          ansible_host: 192.168.0.141
          mac_address: B5-BE-D6-34-57-F0
          name: Node 01 RPi
          username: pi
          username_windows: pi_windows
        k8s-2:
          ansible_host: 192.168.0.161
          mac_address: B5-BE-D6-34-57-F0
          name: Node 02 PC
          username: damian_koper
          username_windows: damian_koper_windows
